name: Continuous Integration - Test File

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  file-changed:
    name: Did the file change
    runs-on: ubuntu-20.04
    outputs:
      changed: ${{ steps.file-check.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: file-check
        name: Check for the file change
        continue-on-error: true
        run: |
          git diff --quiet main..HEAD -- testfile.txt
          echo "::setoutput changed=${?}"
  check-goreleaser:
    needs: file-changed
    name: Check Tested File
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: ${{ needs.file-changed.outputs.changed == '1' }}
        with:
          version: latest
          args: --snapshot --rm-dist --timeout 1h
      - name: Skip Check
        if: ${{ needs.file-changed.outputs.changed == '0' }}
        run: echo "Nothing to see here"
